### ISSUE TITLE
Create usage to IntelliJ IDEA

### ISSUE THREAD

**Issue by fabioparra** [fabioparra/TypeScript#1]
Hi @Dretch, can you create usage to  IntelliJ IDEA with TypeScript 1. 4?

**Comment by Dretch** [comment]
I will have a look at this later.

**Comment by Dretch** [comment]
I think it would be good if this project had a package on NPM (called e.g. "typescript-extjs"). That would make using it easier - users would no longer have to manually replace files.

I will have a look into creating such a package.
