### ISSUE TITLE
Interested in your work

### ISSUE THREAD

**Issue by unional** [fabioparra/TypeScript#9]
Hi,

I'm interested in getting your code to work for TypeScript 1.5.  Instead of creating tsc-extjs, I want to add `--module extjs` support directly.  I did similar thing for `write-umd`, a library that I use to write umd code that works in amd, commonJS and browser global (use namespace reference and direct script tag loading).  Do you mind if I pull your changes in to my fork?

**Comment by Dretch** [comment]
Your project sounds interesting.

As for forking the code - it is open source - you don't have to ask :+1:

**Comment by schwald** [comment]
Hi unional, sounds very interesting. Have you got the code working with Typescript 1.5?

**Comment by fabioparra** [comment]
Hi, thanks for your sugestion. I started with 1.5x  release and its almost done:

https://github.com/fabioparra/TypeScript/releases/tag/v1.5

**Comment by torpedro** [comment]
+1

Sounds great! I see you have worked on a release branch. Looking forward to working with 1.5 when it's ready.

**Comment by unional** [comment]
HI @schwald I didn't have time to work on this. Basic transpilation was ok, but resolving `alias`, `requires`, `mixins`, `viewModel`, `viewController`, `super-> callParent/callSuper` etc and supporting `xtype` properly was too much work.

And at the hindsight, I now think it is not a good idea to transcribe to ExtJS because I don't want to let ExtJS to manage all my classes (Ext component or not) while ES6 class system would be sufficient.

My two cents,
Uni

**Comment by unional** [comment]
Closing this issue
